services:
  mosquitto:
    restart: always
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/start.sh:/start.sh
      - ./volumes/mosquitto/config:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log

  telegraf:
    restart: always
    image: amd64/telegraf
    container_name: telegraf
    ports:
      - 8125:8125
    volumes:
      - ./volumes/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxDB

  influxDB:
    restart: always
    image: amd64/influxdb:1.8.0
    container_name: influxDB
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./volumes/influx/data:/var/lib/influxdb
