###
GET http://localhost:8080/clients

###
POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "testName1",
  "email": "testEmail1",
  "phone": "+7-111-11-11"
}

###
POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "testName2",
  "email": "testEmail2",
  "phone": "+7-222-22-22"
}

###
POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "testName3",
  "email": "testEmail3",
  "phone": "+7-333-33-33"
}

###
PUT http://localhost:8080/update/2
Content-Type: application/json

{
  "name": "testNameUpdate",
  "email": "testEmailUpdate",
  "phone": "+7-upd-at-e"
}

###
DELETE http://localhost:8080/delete/1
Content-Type: application/json

{
  "name": "testNameUpdate",
  "email": "testEmailUpdate",
  "phone": "+7-upd-at-e"
}